### ISSUE TITLE
啊？

### ISSUE THREAD

**Issue by lingbopro** [Minemetero/minemetero.github.io#1]
这是什么奇奇怪怪的`GitHub Pages` repo  

![Screenshot_20240520_205659_com.lemurbrowser.exts.jpg](https://github.com/Minemetero/minemetero.github.io/assets/148617407/2748b762-d61b-4a18-9f8c-968688cbcdbc)

**Comment by Minemetero** [comment]
我计划中的东西现在还啥也不是

**Comment by lingbopro** [comment]
> 我计划中的东西现在还啥也不是

e

**Comment by Minemetero** [comment]
> > 我计划中的东西现在还啥也不是
> 
> e

)))
